"""Event schemas and envelopes for Kafka message streaming."""

from datetime import datetime, timezone
from typing import Dict, Any, Optional, List, Literal
import uuid
from pydantic import BaseModel, Field, ConfigDict


# ------------------------------------------------------------------------------
# 1. Base Event Envelope
# ------------------------------------------------------------------------------
class BaseEvent(BaseModel):
    """Standardized event envelope wrapping all Kafka messages."""

    event_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    event_type: str
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    producer: str = "customer-voice-ai"
    correlation_id: Optional[str] = None

    model_config = ConfigDict(extra="ignore")


# ------------------------------------------------------------------------------
# 2. Review Created Event (Phase 5)
# ------------------------------------------------------------------------------
class ReviewCreatedPayload(BaseModel):
    """Payload for review.created event dispatched upon ingestion."""

    review_id: str
    product_id: str
    source_id: str
    rating: int = Field(ge=1, le=5)
    review_title: Optional[str] = None
    review_text: str
    location: Optional[str] = None
    created_at: datetime
    ingested_at: datetime
    metadata_json: Dict[str, Any] = Field(default_factory=dict)


class ReviewCreatedEvent(BaseEvent):
    """Dispatched when a new customer review is successfully ingested."""

    event_type: Literal["review.created"] = "review.created"
    data: ReviewCreatedPayload


# ------------------------------------------------------------------------------
# 3. Downstream Event Schemas (Phases 6, 7, 8, 12)
# ------------------------------------------------------------------------------
class ReviewAnalyzedPayload(BaseModel):
    """Payload for review.analyzed event generated by LLM analysis agent."""

    review_id: str
    analysis_id: str
    sentiment: Literal["positive", "neutral", "negative"]
    sentiment_score: float
    category: str
    issue: str
    severity: Literal["low", "medium", "high", "critical"]
    customer_intent: Optional[str] = None
    confidence: float
    analyzed_at: datetime


class ReviewAnalyzedEvent(BaseEvent):
    """Dispatched when a review's structured analysis is complete."""

    event_type: Literal["review.analyzed"] = "review.analyzed"
    data: ReviewAnalyzedPayload


class ReviewEmbeddedPayload(BaseModel):
    """Payload for review.embedded event after vectorization."""

    review_id: str
    embedding_dimension: int
    embedded_at: datetime


class ReviewEmbeddedEvent(BaseEvent):
    """Dispatched when a review's vector embedding is stored."""

    event_type: Literal["review.embedded"] = "review.embedded"
    data: ReviewEmbeddedPayload


class IssueDetectedPayload(BaseModel):
    """Payload for issue.detected event when an anomaly or cluster surge occurs."""

    cluster_id: str
    cluster_title: str
    affected_product_id: str
    wow_change_pct: float
    trend_direction: str
    detected_at: datetime


class IssueDetectedEvent(BaseEvent):
    """Dispatched when an emerging complaint issue is detected."""

    event_type: Literal["issue.detected"] = "issue.detected"
    data: IssueDetectedPayload


class ReportGeneratedPayload(BaseModel):
    """Payload for report.generated event."""

    report_id: str
    title: str
    total_reviews: int
    emerging_issues_count: int
    generated_at: datetime


class ReportGeneratedEvent(BaseEvent):
    """Dispatched when weekly executive intelligence report is compiled."""

    event_type: Literal["report.generated"] = "report.generated"
    data: ReportGeneratedPayload
